// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const RAW_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const RAW_SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Trim to tolerate accidental whitespace in .env values
const SUPABASE_URL = typeof RAW_SUPABASE_URL === 'string' ? RAW_SUPABASE_URL.trim() : RAW_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = typeof RAW_SUPABASE_PUBLISHABLE_KEY === 'string' ? RAW_SUPABASE_PUBLISHABLE_KEY.trim() : RAW_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isValidUrl =
  typeof SUPABASE_URL === "string" &&
  SUPABASE_URL.length > 0 &&
  SUPABASE_URL !== "undefined" &&
  SUPABASE_URL !== "null" &&
  /^https?:\/\//.test(SUPABASE_URL);

const isValidKey =
  typeof SUPABASE_PUBLISHABLE_KEY === "string" &&
  SUPABASE_PUBLISHABLE_KEY.trim().length > 0 &&
  SUPABASE_PUBLISHABLE_KEY.trim() !== "undefined" &&
  SUPABASE_PUBLISHABLE_KEY.trim() !== "null";

const hasConfig = isValidUrl && isValidKey;

export const supabase: ReturnType<typeof createClient<Database>> | null = hasConfig
  ? createClient<Database>(SUPABASE_URL as string, SUPABASE_PUBLISHABLE_KEY as string, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : null;

if (!hasConfig && import.meta.env.DEV) {
  const maskedKey = typeof SUPABASE_PUBLISHABLE_KEY === "string"
    ? SUPABASE_PUBLISHABLE_KEY.slice(0, 6) + "..." + SUPABASE_PUBLISHABLE_KEY.slice(-4)
    : SUPABASE_PUBLISHABLE_KEY;
  console.warn(
    "[Supabase] Invalid configuration detected. Check your .env.local variables:",
    {
      VITE_SUPABASE_URL: SUPABASE_URL,
      VITE_SUPABASE_PUBLISHABLE_KEY: maskedKey,
    }
  );
  console.warn(
    "Expected a full https URL for VITE_SUPABASE_URL and a non-empty anon key for VITE_SUPABASE_PUBLISHABLE_KEY."
  );
}